name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: # 수동으로 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: xxziiko
          svg_out_path: dist/github-contribution-grid-snake.svg


      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}


      - name: Push changes to main
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }} 
          branch: main 
          force: true
